language: python

python:
- "2.7"

env:
- DJANGO=1.10.1

install:
- pip install -r requirements.txt
- pip install codeclimate-test-reporter
- pip install -q Django==$DJANGO

script:
- export DJANGO_SECRETKEY=secret
- coverage run --source=habitica_slack manage.py test

after_script:
- codeclimate-test-reporter --file .coverage

notifications:
  slack:
    secure: "r5Pip72WRWGIa9koX1H6SVh/3NL3XF7haSV6rWhVdlW3jT454rEUAjNLwU5MXFSSzv73IcsybeYrKQx4JeVfEM4HpNV3GTWvlgLbRxjLhOvQAl85+0S6Df+8qMn1wIl6HpAlkAINgWGCZUYyMzf4nL6sZu1Awo4fpcjqW1vucivxJN14iXs8TrtNVT/BVpSQeLECVRByeQ2uk50RCAGz8X06oaJwNmDSoncTybxOgvdu+DbNm+nKNZRtW0559mWV4HoX2MlSr68ucroGPpkYp6x+X7WqWFdOuiq+onH5FMqO9CiqTIaJu93mbswO/8wpJyVXKw9SrcK6Y05GiTe5H5UTyiwREfYf0ZD7jv0AX1tNDExrMlpia40GmCKDNWGvvsSU7beke6UHLJdEqVZOMLHF2zGNnYF1CVKYODT8WpA/G6tIlfReMG8h28KzLnPLeAmtcI8NPK68K/JsYutfo9k8+ssGrQzFjUsKtO27SzBc6TNsCfmUJnNGBsTGaoemN4BJ3MlfPFYHdeJyuuLlPqm8P2G1AttuGkMU/EgxkHEeim7DOh/2iXZ5udgdDj7BRBIJDOV67+9H24y6JebJYITYJ1R+atfbq7dE72i9ksPSk3GuOt9FQHztTX6czFLyCZccIsSB3pM5GuYhwN3IrxTEVjTqtTnIG2jSdt3lWYU="
