language: python

python:
  - "2.7"

env:
  - DJANGO=1.10.1

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO

script:
  - export DJANGO_SECRETKEY=secret
  - python manage.py test
